### ISSUE TITLE
How to stop the animation of the floating action Button ?

### ISSUE THREAD

**Issue by ronastlelobo** [santomegonzalo/react-native-floating-action#61]
I don't want it to be tilted on pressing

**Comment by santomegonzalo** [comment]
What do you want exactly @ronastlelobo ? once you click... you want to stop the animation to show the other buttons? can you give me more details please... 
Thanks

**Comment by santomegonzalo** [comment]
Closing this issue because I need more information about it and the issue was created a month ago.

**Comment by nihp** [comment]
If I am navigating from the one screen to another screen FAB button shows in the another screen.

How can I restrict this action while navigating?

**Comment by santomegonzalo** [comment]
The only way of doing this is to move the button to the top of all screens... if the button lives inside one screen the. you can not do it... this is a restriction from React Native... if you put the button outside the navigator then should work but I’m not 100% sure if that will work on the latest version of react-native-router because it is using native navigators.
