### ISSUE TITLE
[Feature Request] On main button state changed callback

### ISSUE THREAD

**Issue by tsvetan-ganev** [santomegonzalo/react-native-floating-action#66]
First of all, thank you for publishing your great module. It perfectly matches my needs and is customize-able enough for more advanced scenarios as well.

One feature that will make it even better is for the component to accept a callback function which will be triggered every time the state of the main button changes (open/closed). My use-case is that I want to change the main button's background colour when it's active. There is an `onPressMain` callback, but I cannot detect when the user closes the overlay and thus I cannot change the colour to the default one.

**Comment by santomegonzalo** [comment]
hi @tsvetan-ganev thanks for your comments!

You could do the same using `onPressMain(bool)` because that will return true or false and then you can use `onPressBackdrop` ... but for simplicity, I will create a new callback called `onStateChange` so you don't need to listen to both functions.

I will let you know as soon as it's ready :)

**Comment by tyson90** [comment]
Hi, I just created PR #71 with `onStateChange` functionality.

**Comment by santomegonzalo** [comment]
I just merged and release PR #71 ... thanks!

**Comment by santomegonzalo** [comment]
@msevestre I did... could you check again please?
